# Generated by Django 4.2.22 on 2026-01-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='bestseller',
            field=models.BooleanField(default=False),
        ),
    ]
