# Generated by Django 4.2.22 on 2026-01-14 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0002_gig_bestseller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gig',
            name='sizes',
        ),
        migrations.AlterField(
            model_name='gig',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gigs.category'),
        ),
        migrations.AlterField(
            model_name='gig',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='GigSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('FREE', 'Free Size')], max_length=10)),
                ('quantity', models.PositiveIntegerField()),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='gigs.gig')),
            ],
        ),
    ]
