# Generated by Django 4.2.22 on 2026-01-14 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0003_remove_gig_sizes_alter_gig_category_alter_gig_stock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gig',
            name='stock',
        ),
    ]
